/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteRouteImport } from './routes/_painel/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PainelAgendaRouteImport } from './routes/_painel/agenda'
import { Route as PainelAgendamentosRouteImport } from './routes/_painel/agendamentos'
import { Route as PainelClientesRouteImport } from './routes/_painel/clientes'
import { Route as PainelConfiguracoesRouteImport } from './routes/_painel/configuracoes'
import { Route as PainelDashboardRouteImport } from './routes/_painel/dashboard'
import { Route as PainelEquipeRouteImport } from './routes/_painel/equipe'
import { Route as PainelHorariosRouteImport } from './routes/_painel/horarios'
import { Route as PainelServicosRouteImport } from './routes/_painel/servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/_painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelAgendaRoute = PainelAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelAgendamentosRoute = PainelAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelClientesRoute = PainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelDashboardRoute = PainelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelEquipeRoute = PainelEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelHorariosRoute = PainelHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelServicosRoute = PainelServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => PainelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof PainelAgendaRoute
  '/agendamentos': typeof PainelAgendamentosRoute
  '/clientes': typeof PainelClientesRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/equipe': typeof PainelEquipeRoute
  '/horarios': typeof PainelHorariosRoute
  '/servicos': typeof PainelServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof PainelAgendaRoute
  '/agendamentos': typeof PainelAgendamentosRoute
  '/clientes': typeof PainelClientesRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/equipe': typeof PainelEquipeRoute
  '/horarios': typeof PainelHorariosRoute
  '/servicos': typeof PainelServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_painel': typeof PainelRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_painel/agenda': typeof PainelAgendaRoute
  '/_painel/agendamentos': typeof PainelAgendamentosRoute
  '/_painel/clientes': typeof PainelClientesRoute
  '/_painel/configuracoes': typeof PainelConfiguracoesRoute
  '/_painel/dashboard': typeof PainelDashboardRoute
  '/_painel/equipe': typeof PainelEquipeRoute
  '/_painel/horarios': typeof PainelHorariosRoute
  '/_painel/servicos': typeof PainelServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/agendamentos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/horarios'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/agendamentos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipe'
    | '/horarios'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/_painel'
    | '/login'
    | '/_painel/agenda'
    | '/_painel/agendamentos'
    | '/_painel/clientes'
    | '/_painel/configuracoes'
    | '/_painel/dashboard'
    | '/_painel/equipe'
    | '/_painel/horarios'
    | '/_painel/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel': {
      id: '/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel/agenda': {
      id: '/_painel/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof PainelAgendaRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/agendamentos': {
      id: '/_painel/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof PainelAgendamentosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/clientes': {
      id: '/_painel/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof PainelClientesRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/configuracoes': {
      id: '/_painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/dashboard': {
      id: '/_painel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PainelDashboardRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/equipe': {
      id: '/_painel/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof PainelEquipeRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/horarios': {
      id: '/_painel/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof PainelHorariosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/_painel/servicos': {
      id: '/_painel/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof PainelServicosRouteImport
      parentRoute: typeof PainelRouteRoute
    }
  }
}

interface PainelRouteRouteChildren {
  PainelAgendaRoute: typeof PainelAgendaRoute
  PainelAgendamentosRoute: typeof PainelAgendamentosRoute
  PainelClientesRoute: typeof PainelClientesRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelDashboardRoute: typeof PainelDashboardRoute
  PainelEquipeRoute: typeof PainelEquipeRoute
  PainelHorariosRoute: typeof PainelHorariosRoute
  PainelServicosRoute: typeof PainelServicosRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelAgendaRoute: PainelAgendaRoute,
  PainelAgendamentosRoute: PainelAgendamentosRoute,
  PainelClientesRoute: PainelClientesRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelDashboardRoute: PainelDashboardRoute,
  PainelEquipeRoute: PainelEquipeRoute,
  PainelHorariosRoute: PainelHorariosRoute,
  PainelServicosRoute: PainelServicosRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}